apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-news
  namespace: backend
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-pull-secret
          containers:
          - name: python-crawler
            image: hamgeonwook/python-crawler:248
            imagePullPolicy: Always
            command: ["python", "update_news.py"]
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          restartPolicy: Never
