apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-fillings
  namespace: backend
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-pull-secret
          containers:
          - name: python-crawler
            image: hamgeonwook/python-crawler:240
            imagePullPolicy: Always
            command: ["python", "update_fillings.py"]
            env:
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: openai-api-key
                    key: OPENAI_API_KEY
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
              - name: AWS_REGION
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_REGION
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          restartPolicy: Never
