apiVersion: apps/v1
kind: Deployment
metadata:
  name: filling-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filling-service
  template:
    metadata:
      labels:
        app: filling-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-worker-1
                      - k8s-worker-2
      containers:
        - name: filling-service
          image: hamgeonwook/filling-service:260
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: spring
            - containerPort: 8082
              name: spring-actuator
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filling-service
  namespace: backend
spec:
  ports:
    - name: spring
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: spring-actuator
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: filling-service
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: filling-service-hpa
#   namespace: backend
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: filling-service
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
