apiVersion: batch/v1
kind: Job
metadata:
  name: init-chart
  namespace: backend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-worker-1
                      - k8s-worker-2
      containers:
      - name: python-crawler
        image: hamgeonwook/python-crawler:164
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - |
            echo "Waiting for data-service Pod to be Ready..."
            until [ "$(kubectl get pod -n backend -l app=data-service -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}')" == "True" ]; do
              echo "Waiting for data-service to be ready..."
              sleep 5
            done
            echo "data-service is Ready! Running init_chart.py..."
            python init_chart.py
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Never
